name: Build

on:
  workflow_run:
    workflows: ["Static Code Analysis and Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install wheel

      - name: Run build
        run: python setup.py sdist bdist_wheel
